# Generated by Django 3.1.7 on 2021-10-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicraftApp', '0002_registermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='signupmodels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('phNum', models.IntegerField()),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('confpswd', models.CharField(max_length=20)),
            ],
        ),
    ]
