# Generated by Django 3.1.7 on 2021-10-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handicraftApp', '0003_signupmodels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registermodel',
        ),
    ]
