# Generated by Django 3.1.7 on 2021-10-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handicraftApp', '0004_delete_registermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signupmodels',
            new_name='registermodel',
        ),
    ]
