# Generated by Django 3.1.7 on 2021-10-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicraftApp', '0005_auto_20211001_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdetailsmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pquantity', models.IntegerField()),
                ('cname', models.CharField(max_length=40)),
                ('caddress', models.CharField(max_length=100)),
                ('cphnum', models.IntegerField()),
                ('cemail', models.CharField(max_length=40)),
            ],
        ),
    ]
